### PR TITLE
Add in some relevant OSX shortcuts

### PR DESCRIPTION
**Pull request by remybach**
There isn't a way of doing this in Chrome on OSX, so I've set it to be: `super+ctrl+[` & `super+ctrl+]`. This makes sense since `super+shift+[` & `super+shift+]` switches tabs left and right in Chrome on OSX.

### CODE REVIEW

**Comment by remybach** [comment]
Also, I forgot to mention that `super+shift+[` & `super+shift+]` switches tabs left & right in Sublime Text too.

**Comment by mrfr0g** [comment]
I'm using `ctrl+alt+left` and `ctrl+alt+right` for this. Works great.

**Comment by remybach** [comment]
Bump.

Is there any movement on this at all? I think at least _any_ keybindings would be more useful rather than none.

Otherwise, do you know how to override the keybindings in the `Default (OSX).sublime-keymap` that's in `Packages/User`? I tried putting my changes in there, but they only seem to work in the keymap file in `Packages/MoveView`.

**Comment by nh2** [comment]
Are you ok with the bindings proposed in https://github.com/nh2/sublime-text-move-tabs/pull/6?

**Comment by remybach** [comment]
I think the shortcuts I proposed make more sense and are less awkward to carry out to be honest (especially given it's an OSX specific keymap file).

**Pull request closed without merging**
